### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jaredforrest** [cyanomiko/dcnnt-android#25]
There is a typo in a dialogue box, It should be Cancel not Cansel
![Screenshot_20220905-161023](https://user-images.githubusercontent.com/56826080/188479464-e5bf5cc3-9a5c-4f8d-a3e1-5369ec2dff17.png)

**Comment by jaredforrest** [comment]
#26 should fix it

**Comment by cyanomiko** [comment]
https://github.com/cyanomiko/dcnnt-android/pull/26 merged.
